package cloak.fabric

import net.fabricmc.mappings.EntryTriple
import net.fabricmc.stitch.util.FieldNameFinder
import java.io.File

object Stitch {
    fun getAutogeneratedFieldNames(jar : File): Map<EntryTriple, String> = FieldNameFinder().findNames(jar)
}